---
name: Publish package
on:
  workflow_dispatch:
    inputs:
      versionBumpType:
        description: Version bump type
        required: true
        default: patch
        type: choice
        options: [major, minor, patch]
permissions:
  contents: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{ steps.publish.outputs.latest-version }}
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - name: Check permission
        if: ${{ !contains('["17008875","33892812", "86938582"]', github.actor_id) }}
        run: echo 'Permission denied' && exit 1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Compile & Release
        run: bun run release
      - name: Bump versions
        run: |
          # Get new version without actually bumping
          NEW_VERSION=$(npm version ${{ inputs.versionBumpType }} --no-git-tag-version --preid=temp)
          # Revert the temp version bump
          git checkout package.json
          # Update both package.json files without creating git tags
          jq ".version = \"${NEW_VERSION#v}\"" package.json > temp.json && mv temp.json package.json
          cd dist && jq ".version = \"${NEW_VERSION#v}\"" package.json > temp.json && mv temp.json package.json
      - name: Publish package
        run: |
          echo "Publishing version: $(cat package.json | jq -r .version)"
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: publish
        name: Output variables
        run: echo "latest-version=$(npm view your-stable-sdk version)" >> "$GITHUB_OUTPUT"
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: bump sdk version'
